layout_spectrum: 0.51093
typography_spectrum: 0.5416267397813499
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.5266912474762648
  lightness: 0.3268381217494607
  saturation: 0.8537905036937445
  rhythmicContrast: 0.928719769930467
name: Vincent-Test
favicon: null
title: Vincent Image Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
