name: Vincent-Test
favicon: null
layout_spectrum: 0.24896
typography_spectrum: 1
title: Vincent-Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6726245840545744
  lightness: 0.5626622235868126
  saturation: 0.8112096982076764
  rhythmicContrast: 0.14493832853622735
purpose: []
