name: Vincent-Test
favicon: null
layout_spectrum: 0.52177
typography_spectrum: 1
title: Vincent-Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#1c2930'
    - '#d9d6d0'
    - '#415054'
    - '#898b85'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
